pipeline {
    agent any

    tools {
        // Install the Maven version configured as "M3" and add it to the path.
        maven "jenkins-maven"
    }

    stages {
        stage('Checkout') {
            steps {
                // Get some code from a GitHub repository
                git 'https://github.com/jenkins/jenkins-docs/simple-java-maven-app.git'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Approval'){
            steps{
                input "Approve Deployemnt ?"
            }
        }
        stage('Deploy'){
            steps{
                input "echo Deployed"
            }
        }
    }

    post{

    }
}
